apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: shopintelli
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk
  username: dXNlcg==
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: shopintelli
type: Opaque
data:
  app-key: eW91ci1iYXNlNjQtZW5jb2RlZC1hcHAta2V5